import Link from 'next/link';
import { redirect } from 'next/navigation';
import { financialPercent, financialPercentText } from '../../../components/ui/FinancialBar';
import { Empty, Metric, Page } from '../../../components/ui/Page';
import { Status } from '../../../components/ui/Status';
import { getProjectPage, getQuoteProjectDashboard, type ProjectRecord } from '../../../lib/data';
import { canonicalListHref, hasCanonicalListQuery, parseListQuery } from '../../../lib/pagination';
import { Pagination } from '../../../components/ui/Pagination';
import { FilterBar } from '../../../components/ui/FilterBar';
import { bogotaDate } from '../../../lib/money';
import { bogotaDateText, compactMoney, priorityText } from '../../../lib/presentation';
import styles from './projects.module.css';

export default async function Projects({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const params = await searchParams; const options = { sort: ['created_at', 'title', 'status', 'expected_end_date', 'project_value'] as const, defaultSort: 'created_at' as const, filters: { status: ['', 'draft', 'quoted', 'approved', 'in_progress', 'paused', 'finished', 'cancelled'] as const } }; const query = parseListQuery(params, options);
  const [result, dashboard] = await Promise.all([getProjectPage({ q: query.search, status: query.filters.status, sort: query.sort, direction: query.direction, page: query.page, pageSize: query.pageSize }), getQuoteProjectDashboard()]); const canonical = { ...query, page: result.page.page };
  if (!hasCanonicalListQuery(params, canonical, options)) redirect(canonicalListHref('/proyectos', params, canonical, options));
  return <Page title="Portafolio de proyectos" description="Desde la cotización hasta el cierre y pago total." actions={<div className={styles.actions}><Link className={styles.secondary} href="/proyectos/exportar">Exportar Excel</Link><Link className={styles.primary} href="/proyectos/nuevo">+ Nuevo proyecto</Link></div>}>
    <section className={styles.summary} aria-label="Resumen de todo el portafolio"><Metric label="Proyectos" value={String(dashboard.projects.metrics.count)} note={compactMoney(dashboard.projects.metrics.contracted_value)} /><Metric label="Activos" value={String(dashboard.projects.metrics.active_count)} note={compactMoney(dashboard.projects.metrics.active_value)} /><Metric label="Ganancia consolidada" value={compactMoney(dashboard.projects.metrics.consolidated_profit)} note="Según gastos registrados" /></section>
    <form><input type="hidden" name="sort" value={query.sort} /><input type="hidden" name="direction" value={query.direction} />{query.pageSize !== 20 && <input type="hidden" name="pageSize" value={query.pageSize} />}<FilterBar actions={<button className="primary">Aplicar</button>}><label>Buscar<input name="q" defaultValue={query.search} /></label><label>Estado<select name="status" defaultValue={query.filters.status}><option value="">Todos</option><option value="draft">Borrador</option><option value="quoted">Cotizado</option><option value="approved">Aprobado</option><option value="in_progress">En proceso</option><option value="paused">Pausado</option><option value="finished">Finalizado</option><option value="cancelled">Cancelado</option></select></label></FilterBar></form>
    {result.records.length ? <div className={styles.grid}>{result.records.map((project) => { const financial = project.financialSummary; const paidPercent = financialPercent(financial.paid, project.project_value); const paidPercentText = financialPercentText(financial.paid, project.project_value); const delay = delayDays(project); return <article className={styles.card} key={project.id}><div className={styles.head}><div><h2>{project.title}</h2><div className={styles.code}>{project.quote_number} · {project.clients?.name ?? 'Sin cliente'}</div></div><Status value={project.status} /></div><div className={styles.meta}><div><span>Valor</span><strong>{compactMoney(project.project_value)}</strong></div><div><span>Pagado</span><strong>{compactMoney(financial.paid)}</strong></div><div><span>Ganancia</span><strong>{compactMoney(financial.real_profit)}</strong></div><div><span>Responsable</span><strong>{project.responsible}</strong></div><div><span>Finalización</span><strong>{bogotaDateText(project.expected_end_date)}</strong></div><div><span>Prioridad</span><strong>{priorityText(project.priority)}</strong></div></div><div className={styles.track} role="img" aria-label={`${paidPercentText} pagado`}><span style={{ width: `${paidPercent ?? 0}%` }} /></div><div className={styles.foot}><span className={delay ? styles.danger : undefined}>{delay ? `Retraso de ${delay} día(s)` : `${paidPercentText} pagado`}</span><Link href={`/proyectos/${project.id}`}>Ver proyecto →</Link></div></article>; })}</div> : <Empty>No hay proyectos con estos filtros.</Empty>}<Pagination page={result.page} />
  </Page>;
}
function delayDays(project: ProjectRecord) { if (['draft', 'quoted', 'cancelled'].includes(project.status)) return 0; const comparison = project.status === 'finished' ? project.actual_end_date : bogotaDate(); if (!comparison || comparison <= project.expected_end_date) return 0; const expected = new Date(`${project.expected_end_date}T12:00:00-05:00`).getTime(); const actual = new Date(`${comparison}T12:00:00-05:00`).getTime(); return Math.max(0, Math.round((actual - expected) / 86_400_000)); }
