'use client';

import { type RefObject, useRef, useState } from 'react';
import { usePathname, useRouter, useSearchParams } from 'next/navigation';
import { saveBusiness, setBusinessActive } from '../../app/actions/business';
import { money } from '../../lib/money';
import { useNativeFormDraft } from '../../lib/local-draft';
import type { PageInfo } from '../../lib/pagination';
import { categoryOptions, categoryText } from '../../lib/presentation';
import { ConfirmationDialog } from '../ui/ConfirmationDialog';
import { Dialog } from '../ui/Dialog';
import { FilterBar } from '../ui/FilterBar';
import { Pagination } from '../ui/Pagination';
import styles from './manager.module.css';

type Row = Record<string, unknown>; type Kind = 'clients' | 'suppliers' | 'catalog_items';
const labels: Record<string, string> = { name: 'Nombre', client_type: 'Tipo de cliente', contact_name: 'Contacto / asesor', phone: 'Teléfono', email: 'Correo', address: 'Dirección', website: 'Sitio web', description: 'Descripción', code: 'Código', unit: 'Unidad', base_unit_price: 'Precio base', category: 'Categoría' };
const columns: Record<Kind, string[]> = { clients: ['name', 'client_type', 'contact_name', 'phone', 'email', 'address'], suppliers: ['name', 'contact_name', 'phone', 'email', 'website', 'description'], catalog_items: ['code', 'description', 'unit', 'base_unit_price', 'category'] };
const sortable: Record<Kind, string[]> = { clients: ['name', 'client_type', 'is_active'], suppliers: ['name', 'is_active'], catalog_items: ['code', 'description', 'category', 'is_active'] };

export function CatalogManager({ kind, rows, page }: { kind: Kind; rows: Row[]; page: PageInfo }) {
  const router = useRouter(); const pathname = usePathname(); const search = useSearchParams();
  const [editing, setEditing] = useState<Row | null>(null); const [activity, setActivity] = useState<Row | null>(null); const pending = false; const [error, setError] = useState(''); const first = useRef<HTMLInputElement>(null);
  const [saveRequest, setSaveRequest] = useState<{ data: FormData; clear: () => void } | null>(null);
  const update = (changes: Record<string, string | null>) => { const next = new URLSearchParams(search.toString()); Object.entries(changes).forEach(([key, value]) => value ? next.set(key, value) : next.delete(key)); next.set('page', '1'); router.replace(`${pathname}?${next}`, { scroll: false }); };
  const submit = (data: FormData, clear: () => void) => setSaveRequest({ data, clear });
  const confirmSave = async () => { if (!saveRequest) return; await saveBusiness(kind, Object.fromEntries(saveRequest.data)); saveRequest.clear(); setSaveRequest(null); setEditing(null); router.refresh(); };
  const confirmActivity = async () => { if (!activity) return; await setBusinessActive(kind, String(activity.id), activity.is_active === false); setActivity(null); router.refresh(); };
  const sort = search.get('sort') ?? sortable[kind][0]; const direction = search.get('direction') ?? 'desc';
  return <><FilterBar actions={<><button type="button" onClick={() => update({ direction: direction === 'asc' ? 'desc' : 'asc' })}>{direction === 'asc' ? 'Ascendente' : 'Descendente'}</button><button className="primary" type="button" onClick={() => setEditing({})}>+ Crear</button></>}><label>Buscar<input defaultValue={search.get('q') ?? ''} onChange={(event) => update({ q: event.target.value || null })} placeholder="Buscar…" /></label><label>Estado<select value={search.get('status') ?? ''} onChange={(event) => update({ status: event.target.value || null })}><option value="">Todos los estados</option><option value="active">Activos</option><option value="inactive">Inactivos</option></select></label><label>Ordenar por<select value={sort} onChange={(event) => update({ sort: event.target.value })}>{sortable[kind].map((key) => <option key={key}>{labels[key]}</option>)}</select></label></FilterBar>
    {error && <p className={styles.error} role="alert">{error}</p>}<div className={styles.tableWrap}><table><caption className="sr-only">Listado</caption><thead><tr>{columns[kind].map((key) => <th key={key}>{labels[key]}</th>)}<th>Estado</th><th>Acciones</th></tr></thead><tbody>{rows.length ? rows.map((row) => <tr key={String(row.id)}>{columns[kind].map((key) => <td key={key}>{display(key, row[key])}</td>)}<td>{row.is_active === false ? 'Inactivo' : 'Activo'}</td><td><button className={styles.link} type="button" onClick={() => setEditing(row)}>Editar</button><button className={styles.link} type="button" onClick={() => setActivity(row)} disabled={pending}>{row.is_active === false ? 'Reactivar' : 'Desactivar'}</button></td></tr>) : <tr><td colSpan={columns[kind].length + 2}>No hay registros con estos filtros.</td></tr>}</tbody></table></div><Pagination page={page} />
    <Dialog open={editing !== null} title={editing?.id ? 'Editar registro' : 'Nuevo registro'} onClose={() => setEditing(null)} initialFocusRef={first}>{editing && <BusinessForm kind={kind} row={editing} first={first} pending={pending} onClose={() => setEditing(null)} onSubmit={submit} />}</Dialog>
    {saveRequest && <ConfirmationDialog open title="Confirmar guardado" description="Se guardará este registro de negocio." recordName={String(saveRequest.data.get('name') ?? saveRequest.data.get('description') ?? saveRequest.data.get('code') ?? '')} confirmLabel="Guardar" onClose={() => setSaveRequest(null)} onConfirm={confirmSave} />}
    {activity && <ConfirmationDialog open title={activity.is_active === false ? 'Reactivar registro' : 'Desactivar registro'} description={activity.is_active === false ? 'El registro volverá a estar disponible para nuevos movimientos.' : 'Se conservará su historial y dejará de estar disponible para nuevos movimientos.'} recordName={String(activity.name ?? activity.description ?? activity.code)} confirmLabel={activity.is_active === false ? 'Reactivar' : 'Desactivar'} variant="danger" onClose={() => setActivity(null)} onConfirm={confirmActivity} />}
  </>;
}
function display(key: string, value: unknown) { if (key === 'base_unit_price') return money(String(value ?? 0)); if (key === 'category') return categoryText(String(value)); if (key === 'website' && value) return <a href={String(value)} target="_blank" rel="noreferrer">{String(value)}</a>; return String(value || '—'); }
function BusinessForm({ kind, row, first, pending, onClose, onSubmit }: { kind: Kind; row: Row; first: RefObject<HTMLInputElement | null>; pending: boolean; onClose: () => void; onSubmit: (data: FormData, clear: () => void) => void }) { const editing = Boolean(row.id); const { formRef, available, conflict, capture, restore, discard, clearFields, clearDraft } = useNativeFormDraft(kind, String(row.id ?? 'new'), String(row.updated_at ?? '')); return <form ref={formRef} onInput={capture} onChange={capture} onSubmit={(event) => { event.preventDefault(); onSubmit(new FormData(event.currentTarget), clearDraft); }} className={styles.form}>{available && <div role="status">{conflict ? 'El registro cambió desde el borrador.' : 'Hay un borrador sin guardar.'}<button type="button" onClick={restore}>Recuperar borrador</button><button type="button" onClick={discard}>Usar versión actual</button></div>}{editing && <input type="hidden" name="id" value={String(row.id)} />}{columns[kind].map((key, index) => <label key={key}>{labels[key]}{key === 'category' ? <select name={key} defaultValue={String(row[key] ?? 'material')}>{categoryOptions.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select> : key === 'client_type' ? <select name={key} defaultValue={String(row[key] ?? 'Empresa')}><option>Empresa</option><option>Persona natural</option><option>Entidad pública</option></select> : key === 'description' && kind === 'suppliers' ? <textarea name={key} defaultValue={String(row[key] ?? '')} /> : <input ref={index === 0 ? first : undefined} name={key} defaultValue={String(row[key] ?? '')} readOnly={key === 'code'} required={['name', 'client_type', 'description', 'unit', 'base_unit_price'].includes(key)} type={key === 'email' ? 'email' : key === 'website' ? 'url' : key === 'base_unit_price' ? 'number' : 'text'} min={key === 'base_unit_price' ? '0' : undefined} step={key === 'base_unit_price' ? '0.01' : undefined} />}</label>)}<footer><button type="button" className={styles.cancel} onClick={onClose}>Cancelar</button><button type="button" onClick={clearFields}>Limpiar campos</button><button disabled={pending} className={styles.primary}>{pending ? 'Guardando…' : 'Guardar'}</button></footer></form>; }
