'use client';

import { useEffect, useId, useRef, useState } from 'react';
import type { RemoteSearchKind, RemoteSearchResult } from '../../lib/remote-search';

export function RemoteSearchSelect({ kind, value, onSelect, placeholder, disabled = false, defaultResult }: { kind: RemoteSearchKind; value: string; onSelect: (result: RemoteSearchResult | null) => void; placeholder: string; disabled?: boolean; defaultResult?: RemoteSearchResult | null }) {
  const id = useId(); const [text, setText] = useState(defaultResult?.primary ?? ''); const [records, setRecords] = useState<RemoteSearchResult[]>([]); const [loading, setLoading] = useState(false); const [message, setMessage] = useState(''); const controller = useRef<AbortController | null>(null); const query = text.trim(); const canSearch = query.length >= 2;
  useEffect(() => { if (!canSearch) return; const timeout = window.setTimeout(async () => { const next = new AbortController(); controller.current?.abort(); controller.current = next; setLoading(true); setMessage(''); try { const response = await fetch(`/api/search/${kind}?q=${encodeURIComponent(query)}`, { signal: next.signal }); const body = await response.json() as { records?: RemoteSearchResult[]; message?: string }; if (!response.ok) throw new Error(body.message ?? 'No fue posible buscar.'); setRecords(body.records ?? []); } catch (error) { if ((error as Error).name !== 'AbortError') setMessage(error instanceof Error ? error.message : 'No fue posible buscar.'); } finally { if (!next.signal.aborted) setLoading(false); } }, 300); return () => { window.clearTimeout(timeout); controller.current?.abort(); }; }, [canSearch, kind, query]);
  return <div><input value={text} disabled={disabled} aria-controls={`${id}-results`} aria-describedby={message ? `${id}-message` : undefined} placeholder={placeholder} onChange={(event) => { setText(event.target.value); onSelect(null); }} />{value && <small>Selección confirmada.</small>}<div id={`${id}-results`} role="listbox" aria-live="polite">{canSearch && (loading ? 'Buscando…' : records.map((result) => <button type="button" role="option" key={result.id} aria-selected={result.id === value} onClick={() => { onSelect(result); setText(result.primary); setRecords([]); }}><strong>{result.primary}</strong>{result.secondary && <small>{result.secondary}</small>}</button>))}</div>{message && <p id={`${id}-message`} role="alert">{message}</p>}</div>;
}
