import { decimal } from './calculations';
import { createClient } from './supabase/server';

export type ClientReference = { name: string; contact_name?: string | null; email?: string | null; address?: string | null };
export type CompanySettings = { legal_name: string; manager_name: string; manager_role: string; professional_card: string | null; phone: string | null; email: string | null; address: string | null; timezone: 'America/Bogota'; currency_code: 'COP' };
export type ProjectFinancialSummary = { id: string; project_value: string; paid: string; balance: string; expenses: string; budget: string; real_profit: string; projected_profit: string };
export type ProjectRecord = { id: string; client_id: string; title: string; quote_number: string; status: string; priority: string; responsible: string; location: string; start_date: string; expected_end_date: string; actual_end_date: string | null; project_value: string; observations: string; profit_mode: 'value' | 'manual'; initial_profit: string; created_at: string; clients: ClientReference | null };
export type QuoteRecord = { id: string; number: string; title: string; status: string; client_id: string; issued_on: string; valid_until: string; total_amount: string; project_id?: string | null; clients: ClientReference | null; quote_items: { quantity: string }[] };
export type ProjectWithFinancialSummary<T extends { id: string } = { id: string }> = T & { financialSummary: ProjectFinancialSummary };
type QueryResult<T> = { data: T | null; error: { message: string } | null };
type SupabaseLike = { from: (table: string) => any };
const summaryFields = 'id,project_value,paid,balance,expenses,budget,real_profit,projected_profit';
const projectFields = 'id,client_id,title,quote_number,status,priority,responsible,location,start_date,expected_end_date,actual_end_date,project_value,observations,profit_mode,initial_profit,created_at,clients(name,contact_name,address)';
const quoteFields = 'id,number,title,status,client_id,issued_on,valid_until,total_amount,project_id,clients(name,contact_name,address),quote_items(quantity)';
const summaryBatchSize = 500;
function queryError(label: string, error: { message: string } | null) { if (!error) return; console.error(`[datos] ${label}`, error); throw new Error(`No fue posible cargar ${label}: ${error.message}`); }
async function typedRows<T>(label: string, request: PromiseLike<QueryResult<any>>): Promise<T[]> { const { data, error } = await request; queryError(label, error); return (data ?? []) as T[]; }
async function typedSingle<T>(label: string, request: PromiseLike<QueryResult<T>>): Promise<T> { const { data, error } = await request; queryError(label, error); if (!data) throw new Error(`No fue posible cargar ${label}: no hay datos disponibles.`); return data; }
export async function getRows(table: string, select = '*'): Promise<any[]> { const supabase = await createClient(); return typedRows(table, supabase.from(table).select(select)); }
export function attachFinancialSummaries<T extends { id: string }>(projects: T[], summaries: ProjectFinancialSummary[]): ProjectWithFinancialSummary<T>[] { const byProjectId = new Map(summaries.map((summary) => [summary.id, summary])); return projects.map((project) => { const financialSummary = byProjectId.get(project.id); if (!financialSummary) throw new Error(`Inconsistencia de datos: el proyecto ${project.id} no tiene resumen financiero.`); return { ...project, financialSummary }; }); }
async function loadFinancialSummaries(supabase: SupabaseLike, projectIds: string[]) { const batches: string[][] = []; for (let index = 0; index < projectIds.length; index += summaryBatchSize) batches.push(projectIds.slice(index, index + summaryBatchSize)); return (await Promise.all(batches.map((ids) => typedRows<ProjectFinancialSummary>('resúmenes financieros de proyectos', supabase.from('project_financial_summary').select(summaryFields).in('id', ids))))).flat(); }
async function loadProjectsWithFinancialSummary<T extends { id: string }>(supabase: SupabaseLike, request: PromiseLike<QueryResult<any>>, label: string) { const projects = await typedRows<T>(label, request); if (!projects.length) return [] as ProjectWithFinancialSummary<T>[]; return attachFinancialSummaries(projects, await loadFinancialSummaries(supabase, projects.map((project) => project.id))); }
export async function getProjectsWithFinancialSummary(label = 'proyectos') { const supabase = await createClient(); return loadProjectsWithFinancialSummary<ProjectRecord>(supabase, supabase.from('projects').select(projectFields).order('created_at', { ascending: false }), label); }
export type ClientWithStats = { id: string; name: string; client_type: string; contact_name: string | null; phone: string | null; email: string | null; address: string | null; is_active: boolean; projectCount: number; contracted: string };
export async function getClientsWithStats() {
  const supabase = await createClient();
  const [clients, projects] = await Promise.all([
    typedRows<Omit<ClientWithStats, 'projectCount' | 'contracted'>>('clientes', supabase.from('clients').select('id,name,client_type,contact_name,phone,email,address,is_active').order('name')),
    typedRows<{ client_id: string; project_value: string }>('proyectos para clientes', supabase.from('projects').select('client_id,project_value')),
  ]);
  const totals = new Map<string, { count: number; contracted: ReturnType<typeof decimal> }>();
  for (const project of projects) { const current = totals.get(project.client_id) ?? { count: 0, contracted: decimal(0) }; current.count += 1; current.contracted = current.contracted.plus(decimal(project.project_value)); totals.set(project.client_id, current); }
  return clients.map((client) => ({ ...client, projectCount: totals.get(client.id)?.count ?? 0, contracted: (totals.get(client.id)?.contracted ?? decimal(0)).toString() }));
}export async function getQuotesWithPresentationData(label = 'cotizaciones') { const supabase = await createClient(); return typedRows<QuoteRecord>(label, supabase.from('quotes').select(quoteFields).order('issued_on', { ascending: false })); }
export async function getCompanySettings(label = 'configuración de empresa') { const supabase = await createClient(); return typedSingle<CompanySettings>(label, supabase.from('company_settings').select('legal_name,manager_name,manager_role,professional_card,phone,email,address,timezone,currency_code').eq('id', true).single()); }
export async function dashboardData() { const supabase = await createClient(); const [projects, quotes, financial] = await Promise.all([loadProjectsWithFinancialSummary<ProjectRecord>(supabase, supabase.from('projects').select(projectFields).order('created_at', { ascending: false }), 'proyectos del panel'), typedRows<QuoteRecord>('cotizaciones del panel', supabase.from('quotes').select(quoteFields).order('issued_on', { ascending: false })), typedSingle<any>('consolidado financiero del panel', supabase.from('portfolio_financial_summary').select('contracted,paid,balance,expenses,budget,real_profit,projected_profit').single())]); return { projects, quotes, financial }; }
export async function getAnalyticsData() { const supabase = await createClient(); const [projects, quotes, payments, expenses] = await Promise.all([loadProjectsWithFinancialSummary<ProjectRecord>(supabase, supabase.from('projects').select(projectFields), 'proyectos para análisis'), typedRows<QuoteRecord>('cotizaciones para análisis', supabase.from('quotes').select(quoteFields).order('issued_on', { ascending: false })), typedRows<{ project_id: string; payment_date: string; amount: string }>('cobros para análisis', supabase.from('project_payments').select('project_id,payment_date,amount')), typedRows<{ project_id: string; expense_date: string; amount: string }>('gastos para análisis', supabase.from('project_expenses').select('project_id,expense_date,amount'))]); return { projects, quotes, payments, expenses }; }
export function sortProjectsByProfit<T extends { financialSummary: ProjectFinancialSummary }>(projects: T[]): T[] { return [...projects].sort((a, b) => decimal(a.financialSummary.real_profit).comparedTo(decimal(b.financialSummary.real_profit))); }
export async function getFinanceData() { const supabase = await createClient(); const [summary, projects, shares] = await Promise.all([typedSingle<any>('consolidado financiero', supabase.from('portfolio_financial_summary').select('contracted,paid,balance,expenses,budget,real_profit,projected_profit').single()), loadProjectsWithFinancialSummary<ProjectRecord>(supabase, supabase.from('projects').select(projectFields), 'proyectos financieros'), typedRows('distribuciones generales', supabase.from('portfolio_shares').select('*').order('created_at'))]); return { summary, projects: sortProjectsByProfit(projects), shares }; }
export async function getAlertsData() { const supabase = await createClient(); return { projects: await loadProjectsWithFinancialSummary<ProjectRecord>(supabase, supabase.from('projects').select(projectFields), 'proyectos para alertas') }; }
export async function getActiveQuoteOptions() { const supabase = await createClient(); const [clients, catalog] = await Promise.all([typedRows('clientes activos', supabase.from('clients').select('id,name,contact_name,email,address').eq('is_active', true).order('name')), typedRows('catálogo activo', supabase.from('catalog_items').select('id,code,description,unit,base_unit_price,category').eq('is_active', true).order('code'))]); return { clients, catalog }; }


