'use client';

import { useMemo } from 'react';
import { usePathname, useRouter, useSearchParams } from 'next/navigation';
import { FilterBar, FilterTag } from '../ui/FilterBar';
import { Metric } from '../ui/Page';
import { Panel } from '../ui/Panel';
import { ResponsiveTable } from '../ui/ResponsiveTable';
import { Tabs } from '../ui/Tabs';
import { AnalyticsBarChart } from './AnalyticsBarChart';
import { commercialAnalysis, delayDays, managementAnalysis, operationAnalysis, projectStates, quoteStates, type AnalyticsData, type AnalyticsFilters, visibleQuoteStatus } from '../../lib/analytics-data';
import { decimal } from '../../lib/calculations';
import { money } from '../../lib/money';
import { bogotaDateText, priorityText, projectStatusText, quoteStatusText } from '../../lib/presentation';
import styles from './AnalyticsWorkspace.module.css';

type Tab = 'management' | 'operation' | 'commercial';
const tabs = [{ id: 'management', label: 'Gerencia y rentabilidad' }, { id: 'operation', label: 'Operación' }, { id: 'commercial', label: 'Comercial' }];
const fields: Record<Tab, readonly string[]> = { management: ['client', 'project', 'status', 'month'], operation: ['client', 'responsible', 'status', 'priority'], commercial: ['client', 'status', 'month'] };

function Select({ label, value, options, onChange }: { label: string; value?: string; options: { value: string; label: string }[]; onChange: (value: string) => void }) {
  return <label className={styles.control}><span>{label}</span><select value={value ?? ''} onChange={(event) => onChange(event.target.value)}><option value="">Todos</option>{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label>;
}

export function AnalyticsWorkspace({ data }: { data: AnalyticsData }) {
  const router = useRouter(); const pathname = usePathname(); const search = useSearchParams();
  const tab = tabs.some((item) => item.id === search.get('tab')) ? search.get('tab') as Tab : 'management';
  const filters = useMemo(() => Object.fromEntries(fields[tab].map((field) => [field, search.get(`${tab}_${field}`) ?? ''])) as AnalyticsFilters, [search, tab]);
  const update = (changes: Record<string, string | null>) => { const next = new URLSearchParams(search.toString()); Object.entries(changes).forEach(([key, value]) => { if (value) next.set(key, value); else next.delete(key); }); router.replace(`${pathname}?${next.toString()}`, { scroll: false }); };
  const setFilter = (field: string, value: string) => update({ [`${tab}_${field}`]: value || null });
  const setTab = (value: string) => update({ tab: value === 'management' ? null : value });
  const reset = () => update(Object.fromEntries(fields[tab].map((field) => [`${tab}_${field}`, null])));
  const clients = [...new Map([...data.projects, ...data.quotes].map((record) => [record.client_id, record.clients?.name ?? 'Sin cliente'])).entries()].map(([value, label]) => ({ value, label })).sort((a, b) => a.label.localeCompare(b.label));
  const tags = fields[tab].flatMap((field) => filters[field] ? [<FilterTag key={field}>{fieldLabel(field)}: {filterLabel(field, filters[field], data)}</FilterTag>] : []);
  return <section className={styles.workspace}><Tabs items={tabs} value={tab} onChange={setTab} label="Vistas de análisis" />
    {tab === 'management' && <Management data={data} filters={filters} clients={clients} setFilter={setFilter} />}
    {tab === 'operation' && <Operation data={data} filters={filters} clients={clients} setFilter={setFilter} />}
    {tab === 'commercial' && <Commercial data={data} filters={filters} clients={clients} setFilter={setFilter} />}
    <div className={styles.tags}>{tags.length ? tags : <span>Sin filtros activos</span>}<button type="button" className={styles.reset} onClick={reset}>Restablecer filtros</button></div>
  </section>;
}

function Management({ data, filters, clients, setFilter }: ViewProps) { const view = managementAnalysis(data, filters); const projectOptions = data.projects.map((project) => ({ value: project.id, label: project.quote_number || project.title })); return <><FilterBar><Select label="Cliente" value={filters.client} options={clients} onChange={(value) => setFilter('client', value)} /><Select label="Proyecto" value={filters.project} options={projectOptions} onChange={(value) => setFilter('project', value)} /><Select label="Estado" value={filters.status} options={projectStates.map((value) => ({ value, label: projectStatusText(value) }))} onChange={(value) => setFilter('status', value)} /><label className={styles.control}><span>Periodo (mes)</span><input type="month" value={filters.month ?? ''} onChange={(event) => setFilter('month', event.target.value)} /></label></FilterBar><div className={styles.metrics}><Metric label="Registros de movimientos" value={String(view.movements.length)} note="Periodo seleccionado" /><Metric label="Saldo pendiente" value={money(view.balance)} note="Acumulado actual" /><Metric label="Resultado calculado" value={money(view.profit)} note="Acumulado actual" /></div><div className={styles.grid}><Panel title="Cobros, gastos y diferencia" meta="Movimientos del periodo"><AnalyticsBarChart data={view.monthly} label="Cobros, gastos y diferencia por mes" onSelect={(value) => setFilter('month', value)} /></Panel><Panel title="Gastos acumulados por proyecto" meta="Acumulado actual"><AnalyticsBarChart data={view.expenses} label="Gastos acumulados por proyecto" onSelect={(value) => setFilter('project', value)} /></Panel><Panel title="Saldo pendiente por cliente" meta="Acumulado actual"><AnalyticsBarChart data={view.balances} label="Saldo pendiente por cliente" onSelect={(value) => setFilter('client', value)} /></Panel><Panel title="Resultado y margen por proyecto" meta="Acumulado actual"><ResponsiveTable label="Resultado y margen por proyecto"><thead><tr><th>Proyecto</th><th>Estado</th><th>Resultado</th><th>Margen</th></tr></thead><tbody>{view.projects.length ? view.projects.map((project) => <tr key={project.id}><td>{project.quote_number || project.title}</td><td>{projectStatusText(project.status)}</td><td>{money(project.financialSummary.real_profit)}</td><td>{decimal(project.project_value).isZero() ? 'No calculable' : `${decimal(project.financialSummary.real_profit).div(project.project_value).times(100).toFixed(1)}%`}</td></tr>) : <EmptyRow columns={4} />}</tbody></ResponsiveTable></Panel></div></> }

function Operation({ data, filters, clients, setFilter }: ViewProps) { const view = operationAnalysis(data, filters); const people = [...new Set(data.projects.map((project) => project.responsible).filter(Boolean))].sort(); return <><FilterBar><Select label="Cliente" value={filters.client} options={clients} onChange={(value) => setFilter('client', value)} /><Select label="Responsable" value={filters.responsible} options={people.map((value) => ({ value, label: value }))} onChange={(value) => setFilter('responsible', value)} /><Select label="Estado" value={filters.status} options={projectStates.map((value) => ({ value, label: projectStatusText(value) }))} onChange={(value) => setFilter('status', value)} /><Select label="Prioridad" value={filters.priority} options={['low', 'medium', 'high', 'critical'].map((value) => ({ value, label: priorityText(value) }))} onChange={(value) => setFilter('priority', value)} /></FilterBar><div className={styles.grid}><Panel title="Proyectos por estado"><AnalyticsBarChart data={view.byStatus} count label="Proyectos por estado" onSelect={(value) => setFilter('status', value)} /></Panel><Panel title="Activos por responsable" meta="Distribución de proyectos, no horas"><AnalyticsBarChart data={view.byResponsible} count label="Proyectos activos por responsable" onSelect={(value) => setFilter('responsible', value)} /></Panel><Panel title="Cronograma y retrasos"><ResponsiveTable label="Cronograma y retrasos"><thead><tr><th>Proyecto</th><th>Responsable</th><th>Inicio</th><th>Prevista</th><th>Real</th><th>Retraso</th></tr></thead><tbody>{view.projects.length ? view.projects.map((project) => <tr key={project.id}><td>{project.quote_number || project.title}</td><td>{project.responsible}</td><td>{bogotaDateText(project.start_date)}</td><td>{bogotaDateText(project.expected_end_date)}</td><td>{bogotaDateText(project.actual_end_date)}</td><td>{delayDays(project) ? `${delayDays(project)} días` : '—'}</td></tr>) : <EmptyRow columns={6} />}</tbody></ResponsiveTable></Panel></div></> }

function Commercial({ data, filters, clients, setFilter }: ViewProps) { const view = commercialAnalysis(data, filters); return <><FilterBar><Select label="Cliente" value={filters.client} options={clients} onChange={(value) => setFilter('client', value)} /><Select label="Estado" value={filters.status} options={quoteStates.map((value) => ({ value, label: quoteStatusText(value) }))} onChange={(value) => setFilter('status', value)} /><label className={styles.control}><span>Emisión (mes)</span><input type="month" value={filters.month ?? ''} onChange={(event) => setFilter('month', event.target.value)} /></label></FilterBar><div className={styles.metrics}><Metric label="Valor aprobado" value={money(view.approvedValue)} note="Estado actual de cotizaciones emitidas" /><Metric label="Propuestas vigentes" value={String(view.validSent)} note="Enviadas y vigentes" /><Metric label="Vencidas" value={String(view.expired)} note="Estado visible actual" tone="warning" /><Metric label="Aprobación" value={view.approval} note="Aprobadas / decisiones tomadas" /></div><div className={styles.grid}><Panel title="Cotizaciones por estado"><AnalyticsBarChart data={view.byStatus} count label="Cotizaciones por estado" onSelect={(value) => setFilter('status', value)} /></Panel><Panel title="Cotizaciones emitidas por mes"><AnalyticsBarChart data={view.byMonth} label="Valor emitido por mes" onSelect={(value) => setFilter('month', value)} /></Panel><Panel title="Valor cotizado por cliente"><AnalyticsBarChart data={view.byClient} label="Valor cotizado por cliente" onSelect={(value) => setFilter('client', value)} /></Panel></div><Panel title="Detalle de cotizaciones" meta={`${view.quotes.length} registros encontrados`}><ResponsiveTable label="Detalle de cotizaciones"><thead><tr><th>Número</th><th>Cliente</th><th>Emisión</th><th>Estado</th><th>Valor</th></tr></thead><tbody>{view.quotes.length ? view.quotes.map((quote) => <tr key={quote.id}><td>{quote.number}</td><td>{quote.clients?.name ?? 'Sin cliente'}</td><td>{bogotaDateText(quote.issued_on)}</td><td>{quoteStatusText(visibleQuoteStatus(quote))}</td><td>{money(quote.total_amount)}</td></tr>) : <EmptyRow columns={5} />}</tbody></ResponsiveTable></Panel></> }

type ViewProps = { data: AnalyticsData; filters: AnalyticsFilters; clients: { value: string; label: string }[]; setFilter: (field: string, value: string) => void };
function EmptyRow({ columns }: { columns: number }) { return <tr><td colSpan={columns}>Sin registros</td></tr>; }
function fieldLabel(field: string) { return ({ client: 'Cliente', project: 'Proyecto', responsible: 'Responsable', status: 'Estado', priority: 'Prioridad', month: 'Mes' } as Record<string, string>)[field] ?? field; }
function filterLabel(field: string, value: string, data: AnalyticsData) { if (field === 'client') return [...data.projects, ...data.quotes].find((record) => record.client_id === value)?.clients?.name ?? value; if (field === 'project') return data.projects.find((project) => project.id === value)?.quote_number ?? value; if (field === 'status') return projectStates.includes(value) ? projectStatusText(value) : quoteStatusText(value); if (field === 'priority') return priorityText(value); return value; }
