'use client';

import { useState, useTransition } from 'react';
import { usePathname, useRouter, useSearchParams } from 'next/navigation';
import { reopenDistribution, saveDistribution, setDistributionActive, settleDistribution } from '../../app/actions/distributions';
import type { Distribution, DistributionMetrics } from '../../lib/distributions-data';
import { money } from '../../lib/money';
import { bogotaDateText, shareModeText } from '../../lib/presentation';
import { ConfirmationDialog } from '../ui/ConfirmationDialog';
import { Metric } from '../ui/Page';
import { Pagination } from '../ui/Pagination';
import { Panel } from '../ui/Panel';
import { ResponsiveTable } from '../ui/ResponsiveTable';
import styles from './DistributionWorkspace.module.css';

export function DistributionWorkspace({ records, page, metrics }: { records: Distribution[]; page: { page: number; pageSize: 20 | 50 | 100; total: number; pageCount: number; from: number; to: number; hasPrevious: boolean; hasNext: boolean }; metrics: DistributionMetrics }) {
  const router = useRouter(); const pathname = usePathname(); const search = useSearchParams(); const [editing, setEditing] = useState<Distribution | null>(null); const [confirm, setConfirm] = useState<{ action: 'settle' | 'reopen' | 'active'; row: Distribution } | null>(null); const [pending, start] = useTransition(); const [error, setError] = useState('');
  const update = (values: Record<string, string | null>) => { const next = new URLSearchParams(search.toString()); Object.entries(values).forEach(([key, value]) => value ? next.set(key, value) : next.delete(key)); next.set('tab', 'distribution'); next.set('distribution_page', '1'); router.replace(`${pathname}?${next}`, { scroll: false }); };
  const action = () => { if (!confirm) return; setError(''); start(async () => { try { if (confirm.action === 'settle') await settleDistribution({ id: confirm.row.id }); if (confirm.action === 'reopen') await reopenDistribution(confirm.row.id); if (confirm.action === 'active') await setDistributionActive({ id: confirm.row.id, isActive: !confirm.row.is_active }); setConfirm(null); router.refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'No fue posible completar la acción.'); } }); };
  return <section className={styles.workspace}><div className={styles.filters}><label>Buscar participante<input defaultValue={search.get('distribution_q') ?? ''} onChange={(event) => update({ distribution_q: event.target.value || null })} /></label><label>Estado<select value={search.get('distribution_activity') ?? ''} onChange={(event) => update({ distribution_activity: event.target.value || null })}><option value="">Todos</option><option value="active">Activas</option><option value="inactive">Inactivas</option></select></label><label>Pago<select value={search.get('distribution_payment') ?? ''} onChange={(event) => update({ distribution_payment: event.target.value || null })}><option value="">Todos</option><option value="paid">Pagadas</option><option value="pending">Pendientes</option></select></label><button type="button" onClick={() => setEditing({ id: '', participant: '', mode: 'percent', value: '0', basis: 'portfolio_profit', is_active: true, is_paid: false, paid_on: null, paid_amount: null, created_at: '' })}>+ Nueva distribución</button></div>
    <div className={styles.metrics}><Metric label="Resultado actual" value={money(metrics.result)} note="Ganancia real consolidada"/><Metric label="Asignado" value={money(metrics.assigned)} note="Reglas activas pendientes"/><Metric label="Pagado acumulado" value={money(metrics.paid)} note="Importe congelado"/><Metric label="Pendiente" value={money(metrics.pending)} note="Por liquidar"/><Metric label={metrics.overAssigned ? 'Excedente asignado' : 'Disponible'} value={money(metrics.available)} note={metrics.overAssigned ? 'Las reglas superan el resultado; puede guardarlas.' : 'Después de pagos y reglas'} tone={metrics.overAssigned ? 'danger' : 'success'}/></div>
    {metrics.overAssigned && <p className={styles.alert} role="alert">Hay sobreasignación. La distribución no se bloquea, pero el disponible es negativo.</p>}
    <Panel title="Participaciones" meta="Los importes pagados son instantáneas auditables."><ResponsiveTable label="Distribuciones generales"><thead><tr><th>Participante</th><th>Regla</th><th>Importe actual</th><th>Pagado congelado</th><th>Estado</th><th>Fecha</th><th>Acciones</th></tr></thead><tbody>{records.map((row) => <tr key={row.id}><td>{row.participant}</td><td>{shareModeText(row.mode)} · {row.mode === 'percent' ? `${row.value}%` : money(row.value)}</td><td>{money(row.mode === 'percent' ? String(Number(metrics.result) * Number(row.value) / 100) : row.value)}</td><td>{row.paid_amount ? money(row.paid_amount) : '—'}</td><td>{row.is_paid ? 'Pagada' : row.is_active ? 'Pendiente' : 'Inactiva'}</td><td>{bogotaDateText(row.paid_on)}</td><td className={styles.rowActions}><button type="button" onClick={() => setEditing(row)}>Editar</button>{row.is_paid ? <button type="button" onClick={() => setConfirm({ action: 'reopen', row })}>Reabrir pago</button> : <button type="button" onClick={() => setConfirm({ action: 'settle', row })}>Marcar pagada</button>}<button type="button" onClick={() => setConfirm({ action: 'active', row })}>{row.is_active ? 'Desactivar' : 'Reactivar'}</button></td></tr>)}</tbody></ResponsiveTable><Pagination page={page} pageParam="distribution_page" pageSizeParam="distribution_pageSize" /></Panel>
    {editing && <Editor row={editing} onClose={() => setEditing(null)} onSave={(data) => { setError(''); start(async () => { try { await saveDistribution(data); setEditing(null); router.refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'No fue posible guardar.'); } }); }} pending={pending} />}
    {error && <p className={styles.error} role="alert">{error}</p>}
    {confirm && <ConfirmationDialog open title={confirm.action === 'settle' ? 'Confirmar pago' : confirm.action === 'reopen' ? 'Reabrir pago' : `${confirm.row.is_active ? 'Desactivar' : 'Reactivar'} distribución`} recordName={confirm.row.participant} description={confirm.action === 'settle' ? 'El importe se calculará y congelará en el servidor con el resultado actual.' : confirm.action === 'reopen' ? 'Se limpiarán el importe congelado y la fecha de pago para permitir correcciones.' : 'Cambiará la participación en los totales pendientes; los pagos históricos se conservan.'} confirmLabel={confirm.action === 'settle' ? 'Marcar como pagada' : confirm.action === 'reopen' ? 'Reabrir pago' : confirm.row.is_active ? 'Desactivar' : 'Reactivar'} variant={confirm.action === 'settle' ? 'warning' : 'danger'} pending={pending} onClose={() => setConfirm(null)} onConfirm={action} />}
  </section>;
}

function Editor({ row, onClose, onSave, pending }: { row: Distribution; onClose: () => void; onSave: (value: { id?: string; participant: string; mode: 'percent' | 'fixed'; value: string }) => void; pending: boolean }) { const [participant, setParticipant] = useState(row.participant); const [mode, setMode] = useState(row.mode); const [value, setValue] = useState(row.value); return <div className={styles.editor} role="region" aria-label="Editar distribución"><h2>{row.id ? 'Editar distribución' : 'Nueva distribución'}</h2>{row.is_paid && <p>Las reglas económicas pagadas están bloqueadas. Reabra el pago para cambiarlas.</p>}<label>Participante<input value={participant} disabled={row.is_paid} onChange={(event) => setParticipant(event.target.value)} /></label><label>Modalidad<select value={mode} disabled={row.is_paid} onChange={(event) => setMode(event.target.value as typeof mode)}><option value="percent">Porcentaje</option><option value="fixed">Valor fijo</option></select></label><label>{mode === 'percent' ? 'Porcentaje (0–100)' : 'Valor'}<input type="number" min="0" max={mode === 'percent' ? '100' : undefined} step="0.01" value={value} disabled={row.is_paid} onChange={(event) => setValue(event.target.value)} /></label><div><button type="button" onClick={onClose}>Cancelar</button><button type="button" disabled={pending || row.is_paid} onClick={() => onSave({ id: row.id || undefined, participant, mode, value })}>{pending ? 'Guardando…' : 'Guardar'}</button></div></div>; }
