'use client';

import { useRef, useState } from 'react';
import { usePathname, useRouter, useSearchParams } from 'next/navigation';
import { reopenDistribution, saveDistribution, setDistributionActive, settleDistribution } from '../../app/actions/distributions';
import type { Distribution, DistributionMetrics, DistributionParticipant } from '../../lib/distributions-data';
import { shareAmount } from '../../lib/calculations';
import { money } from '../../lib/money';
import { useLocalDraft } from '../../lib/local-draft';
import { bogotaDateText, shareModeText } from '../../lib/presentation';
import { ConfirmationDialog } from '../ui/ConfirmationDialog';
import { Metric } from '../ui/Page';
import { Pagination } from '../ui/Pagination';
import { Panel } from '../ui/Panel';
import { ResponsiveTable } from '../ui/ResponsiveTable';
import { Dialog } from '../ui/Dialog';
import { DistributionComparisonChart } from './DistributionComparisonChart';
import { FilterBar } from '../ui/FilterBar';
import { MultiFilter } from '../ui/MultiFilter';
import styles from './DistributionWorkspace.module.css';

type Confirm = { action: 'settle' | 'reopen' | 'active'; row: Distribution };

export function DistributionWorkspace({ records, page, metrics, participants }: { records: Distribution[]; page: { page: number; pageSize: 20 | 50 | 100; total: number; pageCount: number; from: number; to: number; hasPrevious: boolean; hasNext: boolean }; metrics: DistributionMetrics; participants: DistributionParticipant[] }) {
  const router = useRouter(); const pathname = usePathname(); const search = useSearchParams();
  const [editing, setEditing] = useState<Distribution | null>(null); const [confirm, setConfirm] = useState<Confirm | null>(null);
  const [saveRequest, setSaveRequest] = useState<{ payload: { id?: string; request_id?: string; participant: string; mode: 'percent' | 'fixed'; value: string }; clear: () => void } | null>(null);
  const [paidOn, setPaidOn] = useState(bogotaToday()); const pending = false; const error = '';
  const update = (values: Record<string, string | string[] | null>) => { const next = new URLSearchParams(search.toString()); for (const [key, value] of Object.entries(values)) { next.delete(key); for (const item of Array.isArray(value) ? value : value ? [value] : []) next.append(key, item); } next.set('tab', 'distribution'); next.delete('distribution_page'); router.replace(`${pathname}?${next}`, { scroll: false }); };
  const submitConfirm = async () => { if (!confirm) return; const result = confirm.action === 'settle' ? await settleDistribution({ id: confirm.row.id, paidOn }) : confirm.action === 'reopen' ? await reopenDistribution(confirm.row.id) : await setDistributionActive({ id: confirm.row.id, isActive: !confirm.row.is_active }); if (!result.ok) throw new Error(result.message); setConfirm(null); router.refresh(); };
  const amount = (row: Distribution) => shareAmount(row.mode, row.value, metrics.result).toString();
  return <section className={styles.workspace}>
    <FilterBar actions={<button className="primary" type="button" onClick={() => setEditing(newDistribution())}>+ Nueva distribución</button>}><label>Buscar participante<input defaultValue={search.get('distribution_q') ?? ''} onChange={(event) => update({ distribution_q: event.target.value || null })} /></label><MultiFilter label="Estado" values={search.getAll("distribution_activity")} options={[{ value: "active", label: "Activas" }, { value: "inactive", label: "Inactivas" }]} onChange={(values) => update({ distribution_activity: values })} /><MultiFilter label="Pago" values={search.getAll("distribution_payment")} options={[{ value: "paid", label: "Pagadas" }, { value: "pending", label: "Pendientes" }]} onChange={(values) => update({ distribution_payment: values })} /></FilterBar>
    <div className={styles.metrics}><Metric label="Resultado" value={money(metrics.result)} note="Ganancia real consolidada" /><Metric label="Pagado" value={money(metrics.paid)} note="Histórico, activo o inactivo" /><Metric label="Pendiente" value={money(metrics.pending)} note="Reglas activas sin pagar" /><Metric label="Asignado" value={money(metrics.assigned)} note="Pagado más pendiente" /><Metric label="Disponible" value={money(metrics.available)} note={metrics.overAssigned ? 'Negativo: hay excedente asignado.' : 'Resultado menos asignado'} tone={metrics.overAssigned ? 'danger' : 'success'} /></div>
    {metrics.overAssigned && <p className={styles.alert} role="status">Hay sobreasignación. Puede guardar la distribución; revise el disponible negativo.</p>}
    <Panel title="Comparativo por participante" meta="Pagado y pendiente sobre todo el conjunto filtrado"><DistributionComparisonChart participants={participants} /></Panel>
    <Panel title="Participaciones" meta="Los gráficos y métricas consideran todos los registros filtrados."><ResponsiveTable label="Distribuciones generales"><thead><tr><th>Participante</th><th>Regla</th><th>Importe actual</th><th>Pagado congelado</th><th>Estado</th><th>Fecha</th><th>Acciones</th></tr></thead><tbody>{records.length ? records.map((row) => <tr key={row.id}><td>{row.participant}</td><td>{shareModeText(row.mode)} · {row.mode === 'percent' ? `${row.value}%` : money(row.value)}</td><td>{money(amount(row))}</td><td>{row.paid_amount ? money(row.paid_amount) : '—'}</td><td>{row.is_paid ? 'Pagada' : row.is_active ? 'Pendiente' : 'Inactiva'}</td><td>{bogotaDateText(row.paid_on)}</td><td className={styles.rowActions}><button type="button" onClick={() => setEditing(row)}>Editar</button>{row.is_paid ? <button type="button" onClick={() => setConfirm({ action: 'reopen', row })}>Reabrir pago</button> : <button type="button" onClick={() => { setPaidOn(bogotaToday()); setConfirm({ action: 'settle', row }); }}>Marcar pagada</button>}<button type="button" onClick={() => setConfirm({ action: 'active', row })}>{row.is_active ? 'Desactivar' : 'Reactivar'}</button></td></tr>) : <tr><td colSpan={7}>No hay distribuciones con estos filtros.</td></tr>}</tbody></ResponsiveTable><Pagination page={page} pageParam="distribution_page" pageSizeParam="distribution_pageSize" /></Panel>
    {editing && <Editor row={editing} error={error} pending={pending} onClose={() => setEditing(null)} onSave={(payload, clear) => setSaveRequest({ payload, clear })} />}
    {saveRequest && <ConfirmationDialog open title="Confirmar distribución" description="Se guardará esta regla de distribución." recordName={saveRequest.payload.participant} confirmLabel="Guardar" onClose={() => setSaveRequest(null)} onConfirm={async () => { const result = await saveDistribution(saveRequest.payload); if (!result.ok) throw new Error(result.message); saveRequest.clear(); setSaveRequest(null); setEditing(null); router.refresh(); }} />}
    {confirm && <ConfirmationDialog open title={confirm.action === 'settle' ? 'Confirmar pago' : confirm.action === 'reopen' ? 'Reabrir pago' : `${confirm.row.is_active ? 'Desactivar' : 'Reactivar'} distribución`} recordName={confirm.row.participant} description={confirm.action === 'settle' ? 'El importe se calculará y congelará en el servidor.' : confirm.action === 'reopen' ? 'Se limpiarán el importe y fecha congelados para permitir correcciones.' : 'Los pagos históricos se conservan.'} detail={confirm.action === 'settle' ? <label className={styles.paymentDate}>Fecha de pago<input type="date" value={paidOn} onChange={(event) => setPaidOn(event.target.value)} /></label> : undefined} confirmLabel={confirm.action === 'settle' ? 'Marcar como pagada' : confirm.action === 'reopen' ? 'Reabrir pago' : confirm.row.is_active ? 'Desactivar' : 'Reactivar'} variant={confirm.action === 'settle' ? 'warning' : 'danger'} onClose={() => setConfirm(null)} onConfirm={submitConfirm} />}
  </section>;
}

function Editor({ row, error, pending, onClose, onSave }: { row: Distribution; error: string; pending: boolean; onClose: () => void; onSave: (value: { id?: string; request_id?: string; participant: string; mode: 'percent' | 'fixed'; value: string }, clear: () => void) => void }) {
  const [participant, setParticipant] = useState(row.participant); const [mode, setMode] = useState(row.mode); const [value, setValue] = useState(row.value); const [requestId] = useState(() => row.id ? undefined : crypto.randomUUID()); const initialFocus = useRef<HTMLInputElement>(null);
  const draft = useLocalDraft<{ participant: string; mode: 'percent' | 'fixed'; value: string }>('distribution', row.id || 'new');
  const patch = (next: { participant: string; mode: 'percent' | 'fixed'; value: string }) => { setParticipant(next.participant); setMode(next.mode); setValue(next.value); draft.write(next); };
  return <Dialog open title={row.id ? 'Editar distribución' : 'Nueva distribución'} onClose={onClose} locked={pending} initialFocusRef={initialFocus}><form className={styles.editor} onSubmit={(event) => { event.preventDefault(); onSave({ id: row.id || undefined, request_id: requestId, participant, mode, value }, draft.clear); }}><div><button type="button" onClick={() => { const stored = draft.read(); if (stored) patch(stored.value); }}>Recuperar borrador</button><button type="button" onClick={() => { draft.clear(); setParticipant(row.participant); setMode(row.mode); setValue(row.value); }}>Limpiar cambios</button></div>{row.is_paid && <p>Puede cambiar el nombre; modalidad y valor requieren reabrir el pago.</p>}{error && <p className={styles.error} role="alert">{error}</p>}<label>Participante<input ref={initialFocus} required value={participant} onChange={(event) => patch({ participant: event.target.value, mode, value })} /></label><label>Modalidad<select value={mode} disabled={row.is_paid} onChange={(event) => patch({ participant, mode: event.target.value as typeof mode, value })}><option value="percent">Porcentaje</option><option value="fixed">Valor fijo</option></select></label><label>{mode === 'percent' ? 'Porcentaje (0–100)' : 'Valor'}<input type="number" min="0" max={mode === 'percent' ? '100' : undefined} step="0.01" required value={value} disabled={row.is_paid} onChange={(event) => patch({ participant, mode, value: event.target.value })} /></label><div><button type="button" onClick={onClose} disabled={pending}>Cancelar</button><button type="submit" disabled={pending}>{pending ? 'Guardando…' : 'Guardar'}</button></div></form></Dialog>;
}

function newDistribution(): Distribution { return { id: '', participant: '', mode: 'percent', value: '0', basis: 'portfolio_profit', is_active: true, is_paid: false, paid_on: null, paid_amount: null, created_at: '' }; }
function bogotaToday() { const parts = new Intl.DateTimeFormat('en-US', { timeZone: 'America/Bogota', year: 'numeric', month: '2-digit', day: '2-digit' }).formatToParts(new Date()); const part = (type: string) => parts.find((item) => item.type === type)?.value ?? ''; return `${part('year')}-${part('month')}-${part('day')}`; }
