'use client';

import { FormEvent, useMemo, useRef, useState, useTransition } from 'react';
import { usePathname, useRouter, useSearchParams } from 'next/navigation';
import { saveProject, saveProjectRecord } from '../../app/actions/projects';
import { decimal, realPercent, shareAmount } from '../../lib/calculations';
import { money } from '../../lib/money';
import { bogotaDateText, priorityText, profitModeText, projectStatusText, shareBasisText, shareModeText } from '../../lib/presentation';
import type { PageInfo } from '../../lib/pagination';
import { ConfirmationDialog } from '../ui/ConfirmationDialog';
import { Dialog } from '../ui/Dialog';
import { FinancialBar, financialPercentText } from '../ui/FinancialBar';
import { Pagination } from '../ui/Pagination';
import { RemoteSearchSelect } from '../ui/RemoteSearchSelect';
import { Status } from '../ui/Status';
import styles from './ProjectWorkspace.module.css';

export type ProjectDetailSection = 'summary' | 'payments' | 'costs' | 'shares' | 'dates';
type RecordKind = 'payment' | 'expense' | 'budget' | 'share';
type ResultPage = { records: any[]; page: PageInfo };
type Props = { project?: any; summary?: any; section?: ProjectDetailSection; payments?: ResultPage; expenses?: ResultPage; budgets?: ResultPage; shares?: ResultPage };
const statuses = ['draft', 'quoted', 'approved', 'in_progress', 'paused', 'finished', 'cancelled']; const priorities = ['low', 'medium', 'high', 'critical'];
const today = () => new Intl.DateTimeFormat('en-CA', { timeZone: 'America/Bogota' }).format(new Date());
const inThirtyDays = () => { const date = new Date(); date.setDate(date.getDate() + 30); return new Intl.DateTimeFormat('en-CA', { timeZone: 'America/Bogota' }).format(date); };
const values = (event: FormEvent<HTMLFormElement>) => Object.fromEntries(new FormData(event.currentTarget));

export function ProjectWorkspace({ project, summary, section = 'summary', payments, expenses, budgets, shares }: Props) {
  const router = useRouter(); const pathname = usePathname(); const search = useSearchParams(); const [pending, start] = useTransition(); const [notice, setNotice] = useState<{ tone: 'success' | 'error'; text: string } | null>(null);
  const [projectDialog, setProjectDialog] = useState(!project); const [recordDialog, setRecordDialog] = useState<RecordKind | null>(null); const [confirmation, setConfirmation] = useState<{ input: Record<string, FormDataEntryValue>; changes: string[] } | null>(null); const first = useRef<HTMLInputElement>(null);
  const projectId = project?.id as string | undefined; const financial = summary ?? { paid: '0', balance: '0', expenses: '0', budget: '0', real_profit: '0', projected_profit: '0' };
  const defaults = useMemo(() => ({ client_id: project?.client_id ?? '', title: project?.title ?? '', project_value: String(project?.project_value ?? '0'), status: project?.status ?? 'draft', priority: project?.priority ?? 'medium', responsible: project?.responsible ?? '', location: project?.location ?? '', start_date: project?.start_date ?? today(), expected_end_date: project?.expected_end_date ?? inThirtyDays(), actual_end_date: project?.actual_end_date ?? '', observations: project?.observations ?? '', profit_mode: project?.profit_mode ?? 'value', initial_profit: String(project?.initial_profit ?? '0') }), [project]);
  const navigate = (next: ProjectDetailSection) => { const params = new URLSearchParams(search.toString()); if (next === 'summary') params.delete('section'); else params.set('section', next); router.push(`${pathname}${params.size ? `?${params}` : ''}`); };
  const persistProject = (input: Record<string, FormDataEntryValue>) => start(async () => { try { const saved = await saveProject({ ...input, id: projectId }); setNotice({ tone: 'success', text: 'Proyecto guardado.' }); setProjectDialog(false); setConfirmation(null); if (!projectId) router.replace(`/proyectos/${saved.id}`); else router.refresh(); } catch (error) { setNotice({ tone: 'error', text: error instanceof Error ? error.message : 'No fue posible guardar el proyecto.' }); throw error; } });
  function submitProject(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const input = values(event); const changes = sensitiveChanges(project, input); if (projectId && changes.length) setConfirmation({ input, changes }); else persistProject(input); }
  function submitRecord(kind: RecordKind, event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!projectId) return; const form = event.currentTarget; const input = values(event) as Record<string, string | boolean>; if (kind === 'share') input.is_paid = input.is_paid === 'on'; start(async () => { try { await saveProjectRecord(kind, { ...input, project_id: projectId }); form.reset(); setRecordDialog(null); setNotice({ tone: 'success', text: 'Registro guardado.' }); router.refresh(); } catch (error) { setNotice({ tone: 'error', text: error instanceof Error ? error.message : 'No fue posible guardar el registro.' }); } }); }
  if (!project) return <section className={styles.workspace}><ProjectForm defaults={defaults} pending={pending} submit={submitProject} first={first} /><Notice notice={notice} /></section>;
  const budgetPercent = realPercent(financial.budget, project.project_value, 1);
  return <section className={styles.workspace}>
    <header className={styles.projectHeader}><div><span>{project.quote_number || 'Sin identificador'} · {project.clients?.name ?? 'Sin cliente'}</span><h2>{project.title}</h2><p>{project.location || 'Sin ubicación'} · Responsable: {project.responsible || 'Sin responsable'}</p></div><div className={styles.headerMetrics}><Metric label="Valor" value={money(project.project_value)} /><Metric label="Pagado" value={money(financial.paid)} /><Metric label="Saldo" value={money(financial.balance)} /><Metric label="Ganancia" value={money(financial.real_profit)} /></div><button type="button" className={styles.headerButton} onClick={() => setProjectDialog(true)}>Editar proyecto</button></header>
    <nav aria-label="Secciones del proyecto" className={styles.tabs}>{([['summary', 'Resumen'], ['payments', 'Anticipos'], ['costs', 'Gastos y presupuesto'], ['shares', 'Distribución'], ['dates', 'Fechas y condiciones']] as const).map(([id, label]) => <button key={id} type="button" aria-current={section === id ? 'page' : undefined} className={section === id ? styles.active : ''} onClick={() => navigate(id)}>{label}</button>)}</nav><Notice notice={notice} />
    {section === 'summary' && <section className={styles.section}><div className={styles.summaryGrid}><article><h3>Información general</h3><dl><dt>Estado</dt><dd><Status value={project.status} /></dd><dt>Prioridad</dt><dd>{priorityText(project.priority)}</dd><dt>Modelo de ganancia</dt><dd>{profitModeText(project.profit_mode)}</dd><dt>Ganancia proyectada</dt><dd>{money(financial.projected_profit)}</dd></dl></article><article><h3>Observaciones</h3><p>{project.observations || 'Sin observaciones registradas.'}</p><h3>Tiempo invertido</h3><p>{bogotaDateText(project.start_date)} a {bogotaDateText(project.expected_end_date)}</p></article></div><div className={styles.bars}><FinancialBar label="Cobrado" value={financial.paid} total={project.project_value} valueLabel={`${money(financial.paid)} · ${financialPercentText(financial.paid, project.project_value)}`} /><FinancialBar label="Saldo" value={financial.balance} total={project.project_value} valueLabel={`${money(financial.balance)} · ${financialPercentText(financial.balance, project.project_value)}`} /><FinancialBar label="Presupuesto" value={financial.budget} total={project.project_value} valueLabel={`${money(financial.budget)} · ${budgetPercent === null ? 'No calculable' : `${budgetPercent.toString()}%`}`} /></div></section>}
    {section === 'payments' && <section className={styles.section}><SectionHead title="Anticipos" total={money(financial.paid)} action="Registrar anticipo" onClick={() => setRecordDialog('payment')} /><SimpleTable label="Anticipos registrados" columns={['Fecha', 'Valor', 'Medio de pago', 'Observación']} rows={(payments?.records ?? []).map((row) => [bogotaDateText(row.payment_date), money(row.amount), row.payment_method, row.note || '—'])} /><PageControl result={payments} pageParam="payments_page" /></section>}
    {section === 'costs' && <section className={styles.section}><div className={styles.twoCol}><article><SectionHead title="Gastos reales" total={money(financial.expenses)} action="Registrar gasto" onClick={() => setRecordDialog('expense')} /><SimpleTable label="Gastos registrados" columns={['Fecha', 'Categoría', 'Valor', 'Descripción']} rows={(expenses?.records ?? []).map((row) => [bogotaDateText(row.expense_date), row.category, money(row.amount), row.note || '—'])} /><PageControl result={expenses} pageParam="expenses_page" /></article><article><SectionHead title="Presupuesto de costos" total={money(financial.budget)} action="Presupuestar" onClick={() => setRecordDialog('budget')} /><SimpleTable label="Presupuesto registrado" columns={['Categoría', 'Costo base', 'Valor incrementado', 'Descripción']} rows={(budgets?.records ?? []).map((row) => [row.category, money(row.amount ?? row.base_total ?? 0), row.final_total ? money(row.final_total) : '—', row.note || '—'])} /><PageControl result={budgets} pageParam="budgets_page" /></article></div></section>}
    {section === 'shares' && <section className={styles.section}><SectionHead title="Distribución del proyecto" total={`${shares?.page.total ?? 0} registros`} action="Registrar participación" onClick={() => setRecordDialog('share')} /><div className={styles.distributionGrid}>{shares?.records.length ? shares.records.map((row) => { const base = row.basis === 'project_value' ? project.project_value : financial.real_profit; return <article key={row.id}><strong>{row.participant}</strong><span>{shareModeText(row.mode)} · {shareBasisText(row.basis)}</span><b>{money(shareAmount(row.mode, row.value, base))}</b><small>{row.is_paid ? 'Pagada' : 'Pendiente'}{row.paid_on ? ` · ${bogotaDateText(row.paid_on)}` : ''}</small></article>; }) : <p className={styles.empty}>Aún no hay participaciones.</p>}</div><PageControl result={shares} pageParam="shares_page" /></section>}
    {section === 'dates' && <section className={styles.section}><dl className={styles.dateGrid}><dt>Inicio</dt><dd>{bogotaDateText(project.start_date)}</dd><dt>Final prevista</dt><dd>{bogotaDateText(project.expected_end_date)}</dd><dt>Final real</dt><dd>{bogotaDateText(project.actual_end_date)}</dd><dt>Duración</dt><dd>{duration(project.start_date, project.expected_end_date)} días</dd><dt>Retraso</dt><dd>{delayDays(project) ? `${delayDays(project)} días` : '—'}</dd><dt>Prioridad</dt><dd>{priorityText(project.priority)}</dd><dt>Observaciones</dt><dd>{project.observations || 'Sin observaciones registradas.'}</dd></dl></section>}
    <Dialog open={projectDialog} title="Editar proyecto" onClose={() => setProjectDialog(false)} initialFocusRef={first}><ProjectForm defaults={defaults} pending={pending} submit={submitProject} first={first} project={project} /></Dialog><Dialog open={recordDialog !== null} title={recordTitle(recordDialog)} onClose={() => setRecordDialog(null)}>{recordDialog && <RecordForm kind={recordDialog} pending={pending} submit={submitRecord} />}</Dialog>
    {confirmation && <ConfirmationDialog open title="Confirmar cambios sensibles" description={`Se guardarán los siguientes cambios en “${project.title}”:`} detail={<ul>{confirmation.changes.map((change) => <li key={change}>{change}</li>)}</ul>} recordName={project.title} confirmLabel="Guardar cambios" variant={confirmation.changes.some((change) => change === 'Finalizar proyecto' || change === 'Cancelar proyecto') ? 'danger' : 'warning'} onClose={() => setConfirmation(null)} onConfirm={() => new Promise<void>((resolve, reject) => { start(async () => { try { await saveProject({ ...confirmation.input, id: projectId }); setNotice({ tone: 'success', text: 'Proyecto guardado.' }); setProjectDialog(false); setConfirmation(null); router.refresh(); resolve(); } catch (error) { setNotice({ tone: 'error', text: error instanceof Error ? error.message : 'No fue posible guardar el proyecto.' }); reject(error); } }); })} />}
  </section>;
}

function ProjectForm({ defaults, pending, submit, first, project }: { defaults: Record<string, string>; pending: boolean; submit: (event: FormEvent<HTMLFormElement>) => void; first: React.RefObject<HTMLInputElement | null>; project?: any }) { const [clientId, setClientId] = useState(defaults.client_id); const client = project?.clients; return <form onSubmit={submit} className={styles.form}><label>Cliente<RemoteSearchSelect kind="clients" value={clientId} placeholder="Busque un cliente por nombre, contacto o correo" defaultResult={client ? { id: client.id, primary: client.name, secondary: '', metadata: { address: client.address ?? '' } } : null} onSelect={(result) => setClientId(result?.id ?? '')} /><input type="hidden" name="client_id" value={clientId} />{!clientId && <small>Busque y seleccione un cliente activo.</small>}</label><label>Título<input ref={first} name="title" defaultValue={defaults.title} required /></label><label>Valor contratado<input name="project_value" type="number" min="0" step="0.01" defaultValue={defaults.project_value} required /></label><label>Estado<select name="status" defaultValue={defaults.status}>{statuses.map((value) => <option key={value} value={value}>{projectStatusText(value)}</option>)}</select></label><label>Prioridad<select name="priority" defaultValue={defaults.priority}>{priorities.map((value) => <option key={value} value={value}>{priorityText(value)}</option>)}</select></label><label>Responsable<input name="responsible" defaultValue={defaults.responsible} /></label><label>Lugar de ejecución<input name="location" defaultValue={defaults.location} /></label><label>Inicio<input name="start_date" type="date" defaultValue={defaults.start_date} required /></label><label>Final prevista<input name="expected_end_date" type="date" defaultValue={defaults.expected_end_date} required /></label><label>Final real<input name="actual_end_date" type="date" defaultValue={defaults.actual_end_date} /></label><label>Modelo de ganancia<select name="profit_mode" defaultValue={defaults.profit_mode}><option value="value">Valor del proyecto</option><option value="manual">Ganancia manual</option></select></label><label>Ganancia inicial manual<input name="initial_profit" type="number" min="0" step="0.01" defaultValue={defaults.initial_profit} required /></label><label className={styles.full}>Observaciones<textarea name="observations" defaultValue={defaults.observations} rows={3} /></label><button className={styles.primary} disabled={pending || !clientId}>{pending ? 'Guardando…' : 'Guardar proyecto'}</button></form>; }
function RecordForm({ kind, pending, submit }: { kind: RecordKind; pending: boolean; submit: (kind: RecordKind, event: FormEvent<HTMLFormElement>) => void }) { return <form onSubmit={(event) => submit(kind, event)} className={styles.compact}>{kind === 'payment' && <><label>Fecha<input name="payment_date" type="date" defaultValue={today()} required /></label><Amount /><label>Medio de pago<PaymentMethod /></label><label>Observación<input name="note" /></label></>}{kind === 'expense' && <><label>Fecha<input name="expense_date" type="date" defaultValue={today()} required /></label><label>Categoría<input name="category" required /></label><Amount /><label>Medio de pago<PaymentMethod /></label><label>Descripción<input name="note" /></label></>}{kind === 'budget' && <><label>Categoría<input name="category" required /></label><label>Valor presupuestado<input name="amount" type="number" min="0" step="0.01" required /></label><label>Descripción<input name="note" /></label></>}{kind === 'share' && <><label>Participante<input name="participant" required /></label><label>Modalidad<select name="mode"><option value="percent">Porcentaje</option><option value="fixed">Valor fijo</option></select></label><label>Valor<input name="value" type="number" min="0" step="0.01" required /></label><label>Base<select name="basis"><option value="project_value">Valor del proyecto</option><option value="real_profit">Ganancia real</option></select></label><label className={styles.checkbox}><input name="is_paid" type="checkbox" /> Pagada</label><label>Fecha de pago<input name="paid_on" type="date" /></label></>}<button className={styles.primary} disabled={pending}>{pending ? 'Guardando…' : 'Guardar'}</button></form>; }
function Amount() { return <label>Valor<input name="amount" type="number" min="0.01" step="0.01" required /></label>; } function PaymentMethod() { return <select name="payment_method" defaultValue="Transferencia"><option>Transferencia</option><option>Efectivo</option><option>Cheque</option><option>Tarjeta</option><option>Otro</option></select>; }
function Metric({ label, value }: { label: string; value: string }) { return <span>{label}<b>{value}</b></span>; } function Notice({ notice }: { notice: { tone: 'success' | 'error'; text: string } | null }) { return notice ? <p role={notice.tone === 'error' ? 'alert' : 'status'} className={`${styles.notice} ${styles[notice.tone]}`}>{notice.text}</p> : null; } function PageControl({ result, pageParam }: { result?: ResultPage; pageParam: string }) { return result ? <Pagination page={result.page} pageParam={pageParam} /> : null; }
function SectionHead({ title, total, action, onClick }: { title: string; total: string; action: string; onClick: () => void }) { return <div className={styles.sectionHead}><h3>{title} · {total}</h3><button type="button" className={styles.secondary} onClick={onClick}>{action}</button></div>; } function SimpleTable({ label, columns, rows }: { label: string; columns: string[]; rows: React.ReactNode[][] }) { return <div className={styles.tableWrap}><table><caption className="srOnly">{label}</caption><thead><tr>{columns.map((column) => <th key={column}>{column}</th>)}</tr></thead><tbody>{rows.length ? rows.map((row, index) => <tr key={index}>{row.map((cell, cellIndex) => <td key={cellIndex}>{cell}</td>)}</tr>) : <tr><td colSpan={columns.length}>Sin registros</td></tr>}</tbody></table></div>; }
function sensitiveChanges(project: any, input: Record<string, FormDataEntryValue>) { if (!project) return []; const changed = (key: string) => String(project[key] ?? '') !== String(input[key] ?? ''); const moneyChanged = (key: string) => !decimal(project[key] ?? 0).equals(decimal(String(input[key] ?? 0))); const result: string[] = []; if (moneyChanged('project_value')) result.push('Valor contratado'); if (changed('profit_mode')) result.push('Modelo de ganancia'); if (moneyChanged('initial_profit')) result.push('Ganancia inicial manual'); if (changed('expected_end_date') || changed('actual_end_date')) result.push('Fechas de finalización'); if (input.status === 'finished' && project.status !== 'finished') result.push('Finalizar proyecto'); if (input.status === 'cancelled' && project.status !== 'cancelled') result.push('Cancelar proyecto'); return result; }
function recordTitle(kind: RecordKind | null) { return kind === 'payment' ? 'Registrar anticipo' : kind === 'expense' ? 'Registrar gasto' : kind === 'budget' ? 'Agregar presupuesto' : 'Registrar participación'; } function duration(start: string, end: string) { return Math.max(0, Math.round((new Date(`${end}T12:00:00-05:00`).getTime() - new Date(`${start}T12:00:00-05:00`).getTime()) / 86400000)); } function delayDays(project: { status: string; expected_end_date: string; actual_end_date?: string | null }) { const comparison = project.status === 'finished' ? project.actual_end_date : today(); return !comparison || comparison <= project.expected_end_date || ['draft', 'quoted', 'cancelled'].includes(project.status) ? 0 : duration(project.expected_end_date, comparison); }
